CREATE DATABASE Atividade;
USE Atividade;

-- A)Faça scripts para criação de tabelas sem as restrições
CREATE TABLE PRODUCTREQUEST (
	CDPRODUCT SMALLINT,
	CDREQUEST SMALLINT,
	QTAMOUNT INT,
	VLUNITARY DECIMAL(10,2),
);

CREATE TABLE REQUEST (
	CDREQUEST INT,
	DTREQUEST DATE,
	CDCUSTOMER SMALLINT,
	DTDELIVER DATE,
	VLTOTAL DECIMAL(10,2),
);

CREATE TABLE CUSTOMER (
	CDCUSTOMER INT,
	NMCUSTOMER VARCHAR(100),
	NRFONE VARCHAR(11),
	DSADRESS VARCHAR(150),
);

CREATE TABLE PRODUCT (
	CDPRODUCT INT,
	NMPRODUCT VARCHAR(255),
	CDSUPPLIER SMALLINT,
	VLPRICE DECIMAL(10,2),
	QTSTOCK INT,
);

CREATE TABLE SUPPLIER (
	CDSUPPLIER INT,
	NMSUPPLIER VARCHAR(255),
	NRFONE VARCHAR(11),
);

--Colocando restrições

ALTER TABLE PRODUCTREQUEST
ALTER COLUMN CDREQUEST SMALLINT NOT NULL;

ALTER TABLE PRODUCTREQUEST
ALTER COLUMN CDPRODUCT SMALLINT NOT NULL;

ALTER TABLE REQUEST
ALTER COLUMN CDCUSTOMER SMALLINT NOT NULL;

ALTER TABLE PRODUCT
ALTER COLUMN CDSUPPLIER SMALLINT NOT NULL;

ALTER TABLE REQUEST
ALTER COLUMN CDREQUEST SMALLINT NOT NULL;

ALTER TABLE CUSTOMER
ALTER COLUMN CDCUSTOMER SMALLINT NOT NULL;

ALTER TABLE PRODUCT
ALTER COLUMN CDPRODUCT SMALLINT NOT NULL;

ALTER TABLE SUPPLIER 
ALTER COLUMN CDSUPPLIER SMALLINT NOT NULL;

-- B)Faça scripts para criação de Chaves Primarias nas  tabelas.
ALTER TABLE REQUEST 
ADD CONSTRAINT pk_CDREQUEST PRIMARY KEY (CDREQUEST);

ALTER TABLE CUSTOMER
ADD CONSTRAINT pk_CDCUSTOMER PRIMARY KEY (CDCUSTOMER);

ALTER TABLE PRODUCT
ADD CONSTRAINT pk_CDPRODUCT PRIMARY KEY (CDPRODUCT);

ALTER TABLE SUPPLIER
ADD CONSTRAINT pk_CDSUPPLIER PRIMARY KEY (CDSUPPLIER);

--C)Faça scripts para criação de Chaves Secundarias nas tabelas.
ALTER TABLE PRODUCTREQUEST 
ADD CONSTRAINT FK_PRODUCTREQUEST FOREIGN KEY (CDREQUEST) 
REFERENCES REQUEST (CDREQUEST);

ALTER TABLE PRODUCTREQUEST 
ADD CONSTRAINT FK2PRODUCTREQUEST FOREIGN KEY (CDPRODUCT) 
REFERENCES PRODUCT (CDPRODUCT);

ALTER TABLE REQUEST 
ADD CONSTRAINT FK_CUSTOMER FOREIGN KEY (CDCUSTOMER) 
REFERENCES CUSTOMER (CDCUSTOMER);

ALTER TABLE PRODUCT
ADD CONSTRAINT FK_SUPPLIER FOREIGN KEY (CDSUPPLIER) 
REFERENCES SUPPLIER (CDSUPPLIER);

--D)Crie um indice para a chave estrangeira da tabela de produto
CREATE INDEX INDX_SUPPLIER ON PRODUCT(CDSUPPLIER);

--E)Crie um indice para a chave estrangeira da tabela de pedidos
CREATE INDEX INDX_CUSTOMER ON REQUEST(CDCUSTOMER);

--F)Adicione o campo endereço na tabela de fornecedores.
ALTER TABLE SUPPLIER 
ADD NMADDRESS VARCHAR(150);

--G)Faça a inserçao de um novo cliente	
INSERT INTO CUSTOMER (CDCUSTOMER, NMCUSTOMER, NRFONE, DSADRESS) 
VALUES (1,  'Fabiano', 99879375, 'Rua Tijucas, 110, Centro, Joinville - S.C');

--H)Faça a inserção de um novo pedido
INSERT INTO REQUEST (CDREQUEST, DTREQUEST, CDCUSTOMER, DTDELIVER, VLTOTAL) 
VALUES (1, '2008-01-31 14:30:15', 1, '2008-02-05 12:50:35', 54.00);

--I)Atualize o telefone do cliente fabiano.
UPDATE CUSTOMER
SET NRFONE = 99012567
WHERE NRFONE = 99879375

--J)Apague as inserções feitas
DELETE FROM REQUEST;
DELETE FROM CUSTOMER;

--K)Faça o script para excluir todas as tabelas criadas
DROP TABLE CUSTOMER
DROP TABLE REQUEST
DROP TABLE SUPPLIER
DROP TABLE PRODUCT 
DROP TABLE PRODUCTREQUEST